# To parse files generated by Bam-readcount

# Details in field of bam read count

#base:count:avg_mapping_quality:avg_basequality:avg_se_mapping_quality:num_plus_strand:num_minus_strand:avg_pos_as_fraction:avg_num_mismatches_as_fraction:avg_sum_mismatch_qualities:num_q2_containing_reads:avg_distance_to_q2_start_in_q2_reads:avg_clipped_length:avg_distance_to_effective_3p_end
rm(list=ls())
bam_rc.parse <- function(x){
  columns = "base:count:avg_mapping_quality:avg_basequality:avg_se_mapping_quality:num_plus_strand:num_minus_strand:avg_pos_as_fraction:avg_num_mismatches_as_fraction:avg_sum_mismatch_qualities:num_q2_containing_reads:avg_distance_to_q2_start_in_q2_reads:avg_clipped_length:avg_distance_to_effective_3p_end"
  column.names = strsplit(columns, ":")[[1]];rm(columns)
  # get line
  Row = strsplit(x, split = "\t")[[1]]
  # get base counts
  temp <- lapply(Row[-c(1:4)], function(basecnt){
    basecnt = strsplit(basecnt, split = ":")[[1]]
  }) %>% do.call(rbind, .)
  
  colnames(temp) = column.names
  
  dat = data.frame(chr =Row[1],pos = Row[2],ref = Row[3], dp = Row[4],
                   temp)
  
}
strandBias=function(arg1,arg2){
  if(length(arg1)!=length(arg2)){
    error=paste("Parameters with unequal lengths passed as argument!\narg1 =",length(arg1),"; arg2 =",length(arg2))
    message(error)
    return(NA)
  }
  SB=c()
  for (i in seq(1,length(arg1))){
    if(is.na(arg1[i]) | is.na(arg2[i])){
      calc=NA
    }
    else if(arg1[i]<arg2[i]){
      calc=(arg2[i]/arg1[i])*-1
    }
    else{
      calc=(arg1[i]/arg2[i])
    }
    SB=c(SB,calc)
  }
  return(SB)
}

library(dplyr)

setwd("~/Documents/Seafile/NGS-Data-DC/BaseSpace/20201125 Marika ERBB3 iSCREAM/Analysis/bamRC/")

dir.create(file.path("../", "ParsedBAMc"), showWarnings = FALSE)

files=list.files(".",pattern = "bamRC.tsv")
files <- files[grep(pattern = "V1",x = files)]
for (file in files){
  # file="Plasmid_PCR.bamRC.tsv"
  print(paste("Processing",file))
  temp=scan(file, what = "character", sep = "\n")
  dat = lapply(temp, bam_rc.parse) %>% bind_rows()
  dat$chr=as.character(dat$chr)
  dat$pos=as.numeric(dat$pos)
  dat$dp=as.numeric(dat$dp)
  dat$count=as.numeric(dat$count)
  dat[,7:18]=sapply(dat[,7:18],as.numeric)
  dat=dat[dat$base!="=",]
  dat$strandbias=strandBias(dat$num_plus_strand,dat$num_minus_strand)
  dat$AlleleFreq=dat$count/dat$dp
  saveRDS(dat,file=paste("../ParsedBAMc/",gsub(".tsv","",file),".RDS",sep=""))
  write.table(dat,file=paste("../ParsedBAMc/",file,sep=""),sep="\t",row.names = F,col.names = T,quote = F,na = "NA")
  
}
print("Done!")

